services:
  deep-research:
    container_name: deep-research
    build: .
    env_file:
      - .env.local
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
    volumes:
      -  ./:/app/
    tty: true
    stdin_open: true
